/*--------------------------------------------------------------------------------------------------------*\
|*                                      Created by  ADLER THESSIN                                         *|
|*                                    Last modified,  March 20, 2018                                      *|
|*                                                                                                        *|
|*                                   - EV3 Line Follower Tank drive -                                     *|
|*                                            ROBOTC on EV3                                               *|
|*                                                                                                        *|
|*  This program allows a robot to follow a black line.  This particular method uses "Tank Drive" where   *|
|*  each side is controlled individually like a tank.  You may need to play with the light threshold      *|
|*  value to get it just right.                                                                           *|
|*                                                                                                        *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              EV3                 Right motor                         *|
|*    Port C                  motorC              EV3                 Left motor                          *|
|*    Port 1                  color_sensor        EV3                 color sensor                        *|
\*---------------------------------------------------------------------------------------------------4246-*/




#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

TLegoColors currentColor = colorNone;

task checkColor(){
	TLegoColors tempColor = getColorName(colorSensor);
    while(true){
    	if(tempColor != currentColor){
    		currentColor = tempColor;
      }
        wait1Msec(10);
    }
}

task main()
{
  int threshold = 65;

  // create child thread
  startTask(checkColor);

  while(currentColor != colorBlue)
  {
		switch (currentColor)
		{
	  case colorBlue:

	    break;
	  case colorRed:

	    break;
	  default:
	    // sensor sees light:
        if(getColorReflected(colorSensor) > threshold)
        {
          // counter-steer right:
          motor[leftMotor]  = 15;
          motor[rightMotor] = 55;
        }
        // sensor sees dark:
        else
        {
          // counter-steer left:
          motor[leftMotor]  = 55;
          motor[rightMotor] = 15;
        }
	  }
    wait1Msec(10);
	}
}

